<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice - {{ $booking->booking_id }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; line-height: 1.6; padding: 20px; }
        .header { border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
        .business-info { float: left; width: 50%; }
        .invoice-info { float: right; width: 50%; text-align: right; }
        .clear { clear: both; }
        .customer-info { margin-top: 30px; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-block: 20px; }
        th, td { border-bottom: 1px solid #eee; padding: 15px 10px; text-align: left; }
        th { background-color: #f9fafb; font-weight: bold; color: #111827; text-transform: uppercase; font-size: 12px; }
        .total-section { margin-top: 30px; float: right; width: 300px; }
        .total-row { display: flex; justify-content: space-between; padding: 5px 0; }
        .grand-total { font-size: 20px; font-weight: bold; color: #10b981; border-top: 2px solid #eee; margin-top: 10px; padding-top: 10px; }
        .footer { margin-top: 100px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        .status-badge { display: inline-block; padding: 5px 10px; border-radius: 4px; font-weight: bold; font-size: 12px; }
        .status-confirmed { background-color: #d1fae5; color: #065f46; }
        .status-paid { background-color: #dbeafe; color: #1e40af; }
    </style>
</head>
<body>
    <div class="header">
        <div class="business-info">
            <h1 style="color: #10b981; margin: 0;">{{ $tenant->name }}</h1>
            <p style="margin: 5px 0;">{{ $tenant->address ?? 'Address not specified' }}</p>
            <p style="margin: 5px 0;">Phone: {{ $tenant->phone ?? 'N/A' }}</p>
        </div>
        <div class="invoice-info">
            <h2 style="margin: 0;">INVOICE</h2>
            <p style="margin: 5px 0;"><strong>ID:</strong> {{ $booking->booking_id ?? 'B-'.$booking->id }}</p>
            <p style="margin: 5px 0;"><strong>Date:</strong> {{ now()->format('d M, Y') }}</p>
            <p style="margin: 5px 0;">
                <span class="status-badge status-{{ $booking->status }}">
                    {{ strtoupper($booking->status) }}
                </span>
            </p>
        </div>
        <div class="clear"></div>
    </div>

    <div class="customer-info">
        <h3 style="margin-bottom: 10px;">Bill To:</h3>
        <p style="margin: 0;"><strong>{{ $booking->customer_name }}</strong></p>
        <p style="margin: 5px 0;">Event: {{ $booking->event_type }}</p>
        <p style="margin: 5px 0;">Date: {{ \Carbon\Carbon::parse($booking->booking_date)->format('d M, Y') }}</p>
        <p style="margin: 5px 0;">Hall: {{ $booking->hall->name ?? 'Main Hall' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align: center;">Details</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($booking->items as $item)
            <tr>
                <td>Hall Booking ({{ $item->hall_name ?? $item->hall->name ?? 'Hall' }})</td>
                <td style="text-align: center;">{{ $item->event_type }}</td>
                <td style="text-align: right;">৳ {{ number_format($item->sub_total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="total-section">
        <div style="text-align: right;">
            <p><strong>Sub Total:</strong> ৳ {{ number_format($booking->total_amount, 2) }}</p>
            <p><strong>Discount:</strong> ৳ 0.00</p>
            <p><strong>Tax (0%):</strong> ৳ 0.00</p>
            <div class="grand-total">
                Total: ৳ {{ number_format($booking->total_amount, 2) }}
            </div>
            <p style="margin-top: 10px; color: #666;">
                <strong>Paid Amount:</strong> ৳ {{ number_format($booking->advance_amount ?? 0, 2) }}
            </p>
            <p style="color: #dc2626; font-weight: bold;">
                <strong>Balance Due:</strong> ৳ {{ number_format($booking->total_amount - ($booking->advance_amount ?? 0), 2) }}
            </p>
        </div>
    </div>
    <div class="clear"></div>

    <div style="margin-top: 50px;">
        <h3>Terms & Conditions:</h3>
        <p style="font-size: 12px; color: #666;">
            {!! nl2br(e($tenant->invoice_conditions ?? "1. Booking is non-refundable. \n2. Full payment must be made before the event starts. \n3. Management is not responsible for any personal losses.")) !!}
        </p>
    </div>

    <div class="footer">
        <p>Thank you for choosing {{ $tenant->name }}!</p>
        <p>Generated by PranganHQ</p>
    </div>
</body>
</html>
