org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:+UseParallelGC
kotlin.daemon.jvm.options=-Xmx1024m
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Fix Windows cross-drive Kotlin incremental compilation bug (C: pub cache vs D: project)
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.jvm=false
